######################################################################
# Automatically generated by qmake (2.01a) Th 4 thg 12 11 11:25:04 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += gui widgets
# Input
SOURCES += hello.cpp
